language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - 2.6.0

git:
  depth: 10

sudo: false

# we need a more recent cmake than travis/linux provides (at least 2.8.9):
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

cache: bundler

matrix:
  include:
    - script: bundle exec rake rubocop
      rvm: 2.6.0
